/* Shared site footer — single source of truth for every page */
(function () {
  var mount = document.getElementById('siteFooter');
  if (!mount) return;
  mount.outerHTML = "  <footer class=\"footer\">\n\n    <div class=\"footer__inner\">\n      <div class=\"ribbons-wrap\" id=\"footerRibbons\" aria-hidden=\"true\"></div>\n      <div class=\"footer__top\">\n        <div class=\"footer__brand\">\n          <p class=\"footer__tagline\">AN OS for every creator partnerships.</p>\n          <p class=\"footer__copyright\">\u00a9 2026 Inmark. All Rights Reserved</p>\n        </div>\n        <div class=\"footer__cols\">\n          <div class=\"footer__col\">\n            <p class=\"footer__label\">Inmark</p>\n            <a href=\"/#audiences\">For Brand</a>\n            <a href=\"/#audiences\">For Agency</a>\n            <a href=\"/#audiences\">For Influencers</a>\n            <a href=\"/#audiences\">For UGC Creators</a>\n          </div>\n          <div class=\"footer__col\">\n            <p class=\"footer__label\">Support</p>\n            <a href=\"#\">Solutions</a>\n            <a href=\"#\">Products</a>\n            <a href=\"/#faq\">Resources</a>\n            <a href=\"#\">Contact Us</a>\n            <a href=\"/legal.html?d=privacy\">Privacy Policy</a>\n            <a href=\"/legal.html?d=terms\">Terms of Service</a>\n          </div>\n        </div>\n        <div class=\"footer__news\">\n          <p class=\"footer__label\">Subscribe to our newsletter</p>\n          <form class=\"footer__form\" id=\"newsForm\">\n            <input type=\"email\" placeholder=\"Email Address\" aria-label=\"Email address\" required />\n            <button class=\"btn btn--white\" type=\"submit\">Subscribe</button>\n          </form>\n          <p class=\"footer__label footer__label--follow\">Follow us</p>\n          <div class=\"footer__social\">\n            <a href=\"#\" aria-label=\"Instagram\"><svg viewBox=\"0 0 24 24\"><rect x=\"3.5\" y=\"3.5\" width=\"17\" height=\"17\" rx=\"4.5\"/><circle cx=\"12\" cy=\"12\" r=\"4\"/><circle cx=\"17.2\" cy=\"6.8\" r=\"1.1\" fill=\"currentColor\" stroke=\"none\"/></svg></a>\n            <a href=\"#\" aria-label=\"TikTok\"><svg viewBox=\"0 0 24 24\"><path d=\"M14.5 4v9.5a3.75 3.75 0 1 1-3.2-3.71M14.5 5.5c.6 2 2.1 3.4 4.5 3.6\"/></svg></a>\n            <a href=\"#\" aria-label=\"Facebook\"><svg viewBox=\"0 0 24 24\"><path d=\"M14.5 8.5H17V5h-2.5A3.5 3.5 0 0 0 11 8.5V11H8.5v3.5H11V21h3.5v-6.5H17L17.5 11h-3V8.5z\" fill=\"currentColor\" stroke=\"none\"/></svg></a>\n          </div>\n        </div>\n      </div>\n      <div class=\"footer__watermark\" aria-hidden=\"true\">\n        <img src=\"/assets/inmark-logo-light.svg\" alt=\"\" />\n      </div>\n    </div>\n  </footer>";
  var form = document.getElementById('newsForm');
  if (form) form.addEventListener('submit', function (e) {
    e.preventDefault();
    var btn = form.querySelector('button');
    btn.textContent = 'Subscribed \u2713';
    setTimeout(function () { btn.textContent = 'Subscribe'; }, 2500);
  });
})();
