/* Shared blog data — swap for CMS content later */
window.INMARK_POSTS = [
  { slug: 'launch-first-campaign', title: 'How to Launch Your First Campaign on InMark', date: 'Jan 26, 2026', read: '7 Min Read', img: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&q=78&auto=format&fit=crop', excerpt: 'From brief to funded campaign in an afternoon — a practical walkthrough of the whole flow.' },
  { slug: 'escrow-101', title: 'Escrow 101: How Creator Payouts Stay Safe', date: 'Feb 09, 2026', read: '5 Min Read', img: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=78&auto=format&fit=crop', excerpt: 'Why funded campaigns protect both sides, and what "released on approval" really means.' },
  { slug: 'ugc-vs-influencer', title: 'UGC vs Influencer Campaigns: Which Fits Your Brand?', date: 'Mar 03, 2026', read: '6 Min Read', img: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=1200&q=78&auto=format&fit=crop', excerpt: 'Two different jobs, two different briefs. How to choose — and when to run both.' },
  { slug: 'reading-analytics', title: 'Reading Campaign Analytics Like a Strategist', date: 'Mar 21, 2026', read: '8 Min Read', img: 'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=1200&q=78&auto=format&fit=crop', excerpt: 'Reach is a vanity number until you pair it with approval velocity and revision cycles.' },
  { slug: 'brief-templates', title: 'Four Brief Templates Creators Actually Enjoy', date: 'Apr 08, 2026', read: '5 Min Read', img: 'https://images.unsplash.com/photo-1495216875107-c6c043eb703f?w=1200&q=78&auto=format&fit=crop', excerpt: 'Structure beats length. The brief formats that get accepted fastest on InMark.' },
  { slug: 'agency-multibrand', title: 'Running Multi-Brand Campaigns Without Spreadsheets', date: 'Apr 27, 2026', read: '6 Min Read', img: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=78&auto=format&fit=crop', excerpt: 'One workbench per campaign, one status view per client. How agencies stay calm.' },
  { slug: 'ai-drafting', title: 'Letting inmark.ai Draft Your Budget (and When Not To)', date: 'May 14, 2026', read: '7 Min Read', img: 'https://images.unsplash.com/photo-1512428559087-560fa5ceab42?w=1200&q=78&auto=format&fit=crop', excerpt: 'The agent proposes, you dispose. Where AI drafting shines and where humans should override.' },
  { slug: 'creator-rates', title: 'Transparent Rates: Negotiating Without the Awkwardness', date: 'Jun 02, 2026', read: '4 Min Read', img: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&q=78&auto=format&fit=crop', excerpt: 'Counter-offers, usage rights, and why the rate conversation belongs inside the workbench.' }
];
window.INMARK_POST_BODY = [
  'Creator marketing keeps getting described as chaotic — briefs in DMs, budgets in spreadsheets, approvals in screenshots. It does not have to be. The whole point of running campaigns inside one workbench is that every decision leaves a trace, and every trace saves you a meeting.',
  'Start with the brief. A good brief answers three questions in the first five lines: what is being launched, who should care, and what does success look like. Everything else — deliverables, platforms, timing — hangs off those answers. If you cannot write them crisply, the campaign is not ready to fund.',
  'Funding comes next, and this is where escrow changes behaviour on both sides. Creators start work knowing the budget is real. Brands release payment only when deliverables are approved. Nobody chases invoices, and the workbench records exactly when each release happened.',
  'Once content starts landing, resist the urge to react to every data point. Watch approval velocity and revision cycles first — they tell you whether the brief was clear. Reach and engagement matter, but they compound later; process signals show up immediately.',
  'The last step is the one most teams skip: close the loop. Write three lines on what you would change in the next brief while the campaign is still fresh. On InMark that note lives next to the campaign itself, so the next launch starts smarter than the last one.'
];
